# Generated by Django 4.2.7 on 2023-12-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('content', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
    ]
