# Generated by Django 4.2.4 on 2023-09-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_column='Fullname', max_length=70)),
                ('email', models.CharField(db_column='Email', max_length=70)),
                ('birthday', models.DateField(db_column='Birthday')),
                ('age', models.IntegerField(db_column='Age')),
                ('telephone', models.IntegerField(db_column='Telephone')),
                ('sex', models.CharField(db_column='Sex', max_length=45)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
    ]
