# Generated by Django 4.2.3 on 2023-07-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.IntegerField(db_column='RoleID', primary_key=True, serialize=False)),
                ('rolename', models.CharField(db_column='RoleName', max_length=45)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
    ]
