# Generated by Django 4.2.7 on 2023-12-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telephone',
        ),
    ]
