# Generated by Django 4.2.4 on 2023-08-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('prescriptionid', models.AutoField(db_column='PrescriptionID', primary_key=True, serialize=False)),
                ('name_diseaase', models.CharField(db_column='Name_diseaase', max_length=50)),
                ('symptoms', models.CharField(blank=True, db_column='Symptoms', max_length=70, null=True)),
                ('date', models.DateField(db_column='Date')),
                ('medicine', models.CharField(db_column='Medicine', max_length=70)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=100, null=True)),
                ('re_examination_date', models.DateTimeField(db_column='Re-examination_date')),
            ],
            options={
                'db_table': 'prescriptions',
                'managed': False,
            },
        ),
    ]
