# Generated by Django 4.2.4 on 2023-11-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_disease', models.CharField(max_length=200)),
                ('symptoms', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('re_examination_date', models.DateField(blank=True, db_column='re-examination_date', null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'prescriptions',
                'managed': False,
            },
        ),
    ]
