# Generated by Django 4.2.4 on 2023-11-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appid', models.AutoField(db_column='AppID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='Fullname', max_length=70)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('phone', models.IntegerField(db_column='Phone')),
                ('datebooking', models.DateField(db_column='Datebooking')),
                ('note', models.CharField(blank=True, db_column='Note', max_length=100, null=True)),
                ('timebooking', models.TimeField(blank=True, db_column='Timebooking', null=True)),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
    ]
