# Generated by Django 4.2.4 on 2023-08-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('departmentid', models.AutoField(db_column='DepartmentID', primary_key=True, serialize=False)),
                ('named', models.CharField(blank=True, db_column='NameD', max_length=50, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
    ]
