# Generated by Django 4.2.4 on 2023-09-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'managed': False, 'permissions': [('can_manage_departments', 'Can manage departments')]},
        ),
    ]
