# Generated by Django 4.2.4 on 2023-11-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=70, unique=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('images', models.CharField(blank=True, db_column='Images', max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'doctors',
                'managed': False,
            },
        ),
    ]
