# Generated by Django 4.2.4 on 2023-08-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctorid', models.AutoField(db_column='DoctorID', primary_key=True, serialize=False)),
                ('doctorname', models.CharField(db_column='DoctorName', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50, unique=True)),
                ('position', models.CharField(db_column='Position', max_length=50)),
            ],
            options={
                'db_table': 'doctors',
                'managed': False,
            },
        ),
    ]
